### ISSUE TITLE
alpha=0.0f的时候不加载内容

### ISSUE THREAD

**Issue by softwind0214** [Awhisper/VKSafariDomainBridge#4]

**Comment by softwind0214** [comment]
你好，我根据你的思路自己写了个demo，在默认的viewcontroller.viewDidAppear里面加载了这个SFSafariViewController。但是只要alpha=0它就不会加载，这个问题如何解决？

**Comment by Awhisper** [comment]
@softwind0214 可以看一下最新的readme 真的是不推荐适用这个方案了，╮(╯_╰)╭这个方案有太多系统层面遗留的锅。。。非常非常不好使。。

**Comment by softwind0214** [comment]
iOS 11 好像直接把 SFSafariViewController 废掉了，连cookie都不让读了。
clipboard 的解决方案有 sample 吗？我一直没找到。

**Comment by Awhisper** [comment]
@softwind0214 如果你想要ios的demo，直接用UIPastboard 读当前剪切板就好，如果你想问 js 的代码。。。这个。。这个库其实挺有名的。。。如果你身边有前端开发。。。可以问问他们，因为 clipboard的代码就写在github的readme上，对一个含有click事件的dom，注册一个clipboard的剪切监听，完事了。。╮(╯_╰)╭

**Comment by Awhisper** [comment]
@softwind0214 https://github.com/Awhisper/ClipboardJSDemo

**Comment by softwind0214** [comment]
已经甩锅给前端了~
